spring.application.name=quiz

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}
# Fallback for some versions
spring.mongodb.uri=${MONGODB_URI}

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Groq API Configuration
# Bạn có thể nhập nhiều key phân cách bằng dấu phẩy để dự phòng (Fallback)
groq.api.keys=${GROQ_API_KEYS}
groq.api.url=${GROQ_API_URL}
